apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquarium-tank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aquarium-tank
  template:
    metadata:
      labels:
        app: aquarium-tank
    spec:
      containers:
        - name: aquarium-tank
          image: ghcr.io/konstfish/aquarium_tank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi