version: '3.7'
services:
  butterfly:
    build:
      context: .
      dockerfile: butterfly/Dockerfile
      args:
        - COMPONENT=butterfly
    image: ghcr.io/konstfish/aquarium_sprite:latest

  sprite:
    build:
      context: .
      dockerfile: sprite/Dockerfile
      args:
        - COMPONENT=sprite
    image: ghcr.io/konstfish/aquarium_sprite:latest
  
  tetra:
    build:
      context: .
      dockerfile: helper/Dockerfile.gowork
      args:
        - COMPONENT=tetra
    image: ghcr.io/konstfish/aquarium_tetra:latest

  tank:
    build:
      context: .
      dockerfile: tank/Dockerfile
      args:
        - COMPONENT=tank
    image: ghcr.io/konstfish/aquarium_tank:latest