version: '3.7'
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379

  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - 3001:3000 
      - 4317:4317 
      - 4318:4318

  tank:
    image: ghcr.io/konstfish/aquarium_tank:latest
    ports:
      - 3000:3000

  sprite:
    image: ghcr.io/konstfish/aquarium_sprite:latest
    ports:
      - 4001:4001
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379/0
      - OTEL_EXPORTER_OTLP_ENDPOINT=lgtm:4318

  tetra:
    image: ghcr.io/konstfish/aquarium_tetra:latest
    ports:
      - 4002:4002
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=lgtm:4318

  puffer:
    image: ghcr.io/konstfish/aquarium_puffer:latest
    ports:
      - 4003:4003
    depends_on:
      - redis
    links:
      - redis
      - butterfly
      - tetra
    environment:
      - REDIS_URI=redis://redis:6379/0
      - TETRA_URL=http://tetra:4002/tetra/v1/echo
      - BUTTERFLY_URL=http://butterfly:4004/butterfly/v1/error
      - OTEL_EXPORTER_OTLP_ENDPOINT=lgtm:4318

  butterfly:
    image: ghcr.io/konstfish/aquarium_butterfly:latest
    ports:
      - 4004:4004
    depends_on:
      - redis
    links:
      - redis
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=lgtm:4318