version: '3.7'
services:
  sprite:
    build:
      context: .
      dockerfile: sprite/Dockerfile.gowork.sprites
      args:
        - COMPONENT=sprite
  
  tetra:
    build:
      context: .
      dockerfile: helper/Dockerfile.gowork
      args:
        - COMPONENT=tetra

  frontend:
    build: ./aquarium