version: '3.7'
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379

  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - 3001:3000 
      - 4317:4317 
      - 4318:4318

  tank:
    image: ghcr.io/konstfish/aquarium_tank:latest
    ports:
      - 3000:3000

  sprite:
    image: ghcr.io/konstfish/aquarium_sprite:latest
    ports:
      - 4001:4001
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379/0
      - OTEL_EXPORTER_OTLP_ENDPOINT=lgtm:4318