version: '3.7'
services:
  butterfly:
    build:
      context: .
      dockerfile: butterfly/Dockerfile
      args:
        - COMPONENT=butterfly
    image: ghcr.io/konstfish/aquarium_butterfly:latest

  puffer:
    build:
      context: .
      dockerfile: puffer/Dockerfile
      args:
        - COMPONENT=puffer
    image: ghcr.io/konstfish/aquarium_puffer:latest

  sprite:
    build:
      context: .
      dockerfile: sprite/Dockerfile
      args:
        - COMPONENT=sprite
    image: ghcr.io/konstfish/aquarium_sprite:latest
  
  starfish:
    build:
      context: .
      dockerfile: starfish/Dockerfile
      args:
        - COMPONENT=starfish
    image: ghcr.io/konstfish/aquarium_starfish:latest
  
  tetra:
    build:
      context: .
      dockerfile: helper/Dockerfile.gowork
      args:
        - COMPONENT=tetra
    image: ghcr.io/konstfish/aquarium_tetra:latest

  tank:
    build:
      context: .
      dockerfile: tank/Dockerfile
      args:
        - COMPONENT=tank
    image: ghcr.io/konstfish/aquarium_tank:latest