apiVersion: v1
kind: Service
metadata:
  name: aquarium-starfish
  labels:
    app: aquarium-starfish
spec:
  selector:
    app: aquarium-starfish
  ports:
    - protocol: TCP
      name: http
      port: 4005
      targetPort: 4005
