apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: starfish
  labels:
    app: starfish
spec:
  selector:
    matchLabels:
      app: starfish
  endpoints:
  - port: http
    interval: 30s