apiVersion: v1
kind: Service
metadata:
  name: aquarium-sprite
  labels:
    app: aquarium-sprite
spec:
  selector:
    app: aquarium-sprite
  ports:
    - protocol: TCP
      name: backend
      port: 4001
      targetPort: 4001
