apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sprite
  labels:
    app: sprite
spec:
  selector:
    matchLabels:
      app: sprite
  endpoints:
  - port: http
    interval: 30s