apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aquarium-sprite
  labels:
    app: aquarium-sprite
spec:
  selector:
    matchLabels:
      app: aquarium-sprite
  endpoints:
  - port: http
    interval: 30s