apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aquarium-butterfly
  labels:
    app: aquarium-butterfly
spec:
  selector:
    matchLabels:
      app: aquarium-butterfly
  endpoints:
  - port: http
    interval: 30s