apiVersion: v1
kind: Service
metadata:
  name: butterfly
  labels:
    app: butterfly
spec:
  selector:
    app: butterfly
  ports:
    - protocol: TCP
      name: http
      port: 4004
      targetPort: 4004
