apiVersion: v1
kind: Service
metadata:
  name: aquarium-butterfly
spec:
  selector:
    app: aquarium-butterfly
  ports:
    - protocol: TCP
      name: backend
      port: 4004
      targetPort: 4004
