apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aquarium-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: aquarium.app.konst.fish
    http:
      paths:
      - path: /sprites/v1
        pathType: Prefix
        backend:
          service:
            name: aquarium-sprite
            port:
              number: 4001
      - path: /tetra/v1
        pathType: Prefix
        backend:
          service:
            name: aquarium-tetra
            port:
              number: 4002
      - path: /puffer/v1
        pathType: Prefix
        backend:
          service:
            name: aquarium-puffer
            port:
              number: 4003
      - path: /butterfly/v1
        pathType: Prefix
        backend:
          service:
            name: aquarium-butterfly
            port:
              number: 4004
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aquarium-tank
            port:
              number: 3000