apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetra
  labels:
    app: tetra
spec:
  selector:
    matchLabels:
      app: tetra
  endpoints:
  - port: http
    interval: 30s