apiVersion: v1
kind: Service
metadata:
  name: aquarium-tetra
  labels:
    app: aquarium-tetra
spec:
  selector:
    app: aquarium-tetra
  ports:
    - protocol: TCP
      name: http
      port: 4002
      targetPort: 4002
