apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aquarium-tetra
  labels:
    app: aquarium-tetra
spec:
  selector:
    matchLabels:
      app: aquarium-tetra
  endpoints:
  - port: http
    interval: 30s