apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aquarium-puffer
  labels:
    app: aquarium-puffer
spec:
  selector:
    matchLabels:
      app: aquarium-puffer
  endpoints:
  - port: http
    interval: 30s