apiVersion: v1
kind: Service
metadata:
  name: puffer
  labels:
    app: puffer
spec:
  selector:
    app: puffer
  ports:
    - protocol: TCP
      name: http
      port: 4003
      targetPort: 4003
