apiVersion: v1
kind: Service
metadata:
  name: aquarium-puffer
  labels:
    app: aquarium-puffer
spec:
  selector:
    app: aquarium-puffer
  ports:
    - protocol: TCP
      name: backend
      port: 4003
      targetPort: 4003
